name: Deploy google workflow pipelines/consume-weather/pipeline.yaml

on:
  push:
    branches:
      - main
    paths:
      - 'pipelines/consume-weather/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Deploy Workflow
      run: |
        gcloud workflows deploy consume-weather \
          --location=us-central1 \
          --source=pipelines/consume-weather/pipeline.yaml