name: Deploy Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'de-ai23'
        workload_identity_provider: projects/411203856706/locations/global/workloadIdentityPools/github-actions/providers/cloud-functions-example

    - name: 'gcloud config list'
      run: 'gcloud config list'

    - name: Deploy Cloud FunctioN
      run: |
        gcloud functions deploy cloud-functions-example \
          --region=us-central1 \
          --runtime=python310 \
          --trigger-http \
          --entry-point=main\
          --allow-unauthenticated \
          --source=./
