name: Deploy cloud function pipes/weatherapi-raw-weather-clean/src/

on:
  push:
    branches:
      - main
    paths:
      - 'pipes/weatherapi-raw-weather-clean/src/**'


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Deploy cloud function weatherapi-raw-weather-clean
      run: |
        gcloud functions deploy weatherapi-raw-weather-clean \
          --region=us-central1 \
          --runtime=python310 \
          --trigger-http \
          --entry-point=main\
          --allow-unauthenticated \
          --source=pipes/weatherapi-raw-weather-clean/src/
