name: Deploy Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy cloud-functions-example \
          --region=us-central1 \
          --runtime=python310 \
          --trigger-http \
          --entry-point=main\
          --allow-unauthenticated \
          --source=pipes/weatherapi-raw-weather-clean/src/
